name:每日天气推送
on:
  workflow_dispatch:
  schedule:
    # UTC23点 = 北京时间早上7点
    - cron: "0 23 * * *"
jobs:
  weather:
    runs-on: ubuntu-latest
    env:
      SERVERCHAN_SENDKEY: ${{ secrets.SERVERCHAN_SENDKEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python << 'PY'
          import requests, os
          url = "https://wttr.in/Kunming?format=j1"
          resp = requests.get(url,timeout=15).json()
          temp = resp["current_condition"][0]["temp_C"]
          desc = resp["current_condition"][0]["weatherDesc"][0]["value"]
          msg = f"🌤️昆明今日天气：{desc}，温度 {temp}℃"
          sckey = os.environ["SERVERCHAN_SENDKEY"]
          requests.post(f"https://sctapi.ftqq.com/{sckey}.send", data={
              "title":"🌤️每日天气提醒",
              "desp":msg
          })
          PY
